[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pylsltools"
version = "0.0.1"
authors = [
   {name="Jamie Forth", email="j.forth@gold.ac.uk"},
]
description = "Tools for working with LSL data streams."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "AGPL"}

dependencies = [
    "pyxdftools @ git+https://github.com/jamieforth/pyxdf-tools.git",
    "pylsl",
]

[project.urls]
"Homepage" = "https://github.com/jamieforth/pylsl-tools"
"Bug Tracker" = "https://github.com/jamieforth/pylsl-tools/issues"

[project.scripts]
lsl-playback = "pylsltools.playback:main"
lsl-simulate = "pylsltools.simulate:main"
