hostname_device_mapper = {
    'DESKTOP-3R7C1PH': 'eeg-a',
    'DESKTOP-2TI6RBU': 'eeg-b',
    'DESKTOP-MN7K6RM': 'eeg-c',
    'DESKTOP-URRV98M': 'eeg-d',
    'DESKTOP-DATOEVU': 'eeg-e',
    'TABLET-9I44R1AR': 'eeg-f',
    'DESKTOP-SLAKFQE': 'eeg-g',
    'DESKTOP-6FJTJJN': 'eeg-h',
    'DESKTOP-HDOESKS': 'eeg-i',
    'DESKTOP-LIA3G09': 'eeg-j',
    'DESKTOP-V6779I4': 'eeg-k',
    'DESKTOP-PLV2A7L': 'eeg-l',
    'DESKTOP-SSSOE1L': 'eeg-m',
    'DESKTOP-RM16J67': 'eeg-n',
    'DESKTOP-N2RA68S': 'eeg-o',
    'DESKTOP-S597Q21': 'eeg-p',
    'TABLET-06K1PLD4': 'eeg-q',
    'DESKTOP-MK0GQFM': 'eeg-r',
    'DESKTOP-7GV3RJU': 'eeg-s',
    'DESKTOP-S5A1PPK': 'eeg-t',
    'TABLET-3BS4NTP2': 'eeg-u',
    'DESKTOP-QG4CNEV': 'eeg-v',
    'DESKTOP-OAF4OCM': 'eeg-w',
    'DESKTOP-T3RKRMH': 'eeg-cs-v',
}
